schema: http://localhost:3000/dev
documents: "./src/queries/**/*.graphql"
extensions:
  codegen:
    generates:
      ./src/generated/index.ts:
        plugins:
          - typescript
          - typescript-operations
          - typescript-react-apollo
      ./src/generated/schema.graphql:
        plugins:
          - schema-ast
