schema: http://localhost:3000/dev/graphql
# documents: "./src/**/*.graphql"
extensions:
  codegen:
    generates:
      ./src/generated/types.ts:
        plugins:
          - typescript
          - typescript-react-apollo
        config:
          withHooks: true
      ./src/generated/schema.graphql:
        plugins:
          - schema-ast
